terraform {
  required_version = ">= 1.5.0"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5"
    }
  }
}

provider "cloudflare" {
  # auth comes from env var:
  # $CLOUDFLARE_API_TOKEN
  #
  # zone_id and account_id are Terraform input variables,
  # supplied via the *.auto.tfvars.json files generated by generate.sh.
}
