variable "zone_id" {
  type        = string
  description = "Cloudflare zone ID for jabbson.xyz. Populated by dns.auto.tfvars.json."
}

variable "account_id" {
  type        = string
  description = "Cloudflare account ID. Populated by tunnels.auto.tfvars.json."
}

# These are generated into *.auto.tfvars.json by generate.sh
variable "dns_records" {
  type        = map(any)
  description = "Map of DNS record ID -> record attributes. Generated by generate.sh into dns.auto.tfvars.json."
}

variable "tunnels" {
  type        = map(any)
  description = "Map of tunnel ID -> tunnel attributes. Generated by generate.sh into tunnels.auto.tfvars.json."
}

variable "traefik_ip" {
  type        = string
  description = "Public IP of the Traefik reverse proxy host. Injected as content for all A records tagged comment=traefik. Set manually in traefik.auto.tfvars."
}

variable "email_routing_addresses" {
  type = map(object({
    id    = string
    email = string
  }))
  description = "Map of address ID -> destination email address. Generated by generate.sh into email_routing.auto.tfvars.json."
}

variable "email_routing_rules" {
  type = map(object({
    id       = optional(string)
    name     = optional(string)
    enabled  = optional(bool)
    priority = optional(number)
    actions = optional(list(object({
      type  = string
      value = optional(list(string))
    })))
    matchers = optional(list(object({
      type  = optional(string)
      field = optional(string)
      value = optional(string)
    })))
  }))
  description = "Map of rule ID -> routing rule attributes. Generated by generate.sh into email_routing.auto.tfvars.json."
}

variable "email_routing_catch_all" {
  type = object({
    enabled  = bool
    name     = optional(string)
    actions  = list(any)
    matchers = list(any)
  })
  description = "Catch-all email routing rule configuration. Generated by generate.sh into email_routing.auto.tfvars.json."
}
